### ISSUE TITLE
error while : bash step_5.sh

### ISSUE THREAD

**Issue by chandrasekhar-jinendran** [rajesh-iiith/add_ide_features_to_vim#1]
Error while : bash step_5.sh

  File "/home/chandu/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 944
    print( *args, **kwargs )
           ^
SyntaxError: invalid syntax

**Comment by R46narok** [comment]
Use python3.

**Comment by chandrasekhar-jinendran** [comment]
Thanks, now it works.
